### ISSUE TITLE
Error KB import

### ISSUE THREAD

**Issue by LorenzoDonini997** [UNITN-KDI-2020/unitn-kdi-2020-room#11]
Good evening,
I'm Lorenzo Donini, a student of the group covid.
This is to let you know that I have problems with KBimport/excel as I have the following error in the response body:

**504 Gateway time out nginx/1.17.10**

What should I do?

Thanks,

Lorenzo Donini

**Comment by ghost** [comment]
We (geospatial group) have the same problem now! 
Some hourse ago the system worked.

**Comment by simone-bocca** [comment]
Dear all

The error is related to the response delivery.
The concepts are correctly imported, you can check that using the Knowledge Explorer.

You should be able to continue the work.
We will solve the issue.

Thanks
Simone
