### ISSUE TITLE
Evaluation Examples

### ISSUE THREAD

**Issue by TEXflip** [UNITN-KDI-2020/unitn-kdi-2020-room#12]
Good evening,
I can't find the examples for the evaluation part, do they are available?
If not, when will they be available?

Thanks
Michele Tessari

**Comment by simone-bocca** [comment]
Dear Michele

The Evaluation for the last two phases of the methodology is out of class this year.
Regarding the Evaluation on the Informal modeling phase, you can ask more precise info directly to @maurodragoni .

Thanks
Simone
