### ISSUE TITLE
Request of additional information

### ISSUE THREAD

**Issue by ghost** [UNITN-KDI-2020/unitn-kdi-2020-room#13]
Dear all, 
I'am a KE of the geospatial gorup and i kindly ask you if yuo can give us some additional information regarding the formalization (in particular the name formalization) of the individuals in order to create properly the enumeration classes. 

We searched in the latest slides and videos but we didn't find any information: can you help us ? 

Thank you in advance!

**Comment by MayukhBagchiTrento** [comment]
Dear All,

For the concern expressed above, check Protege (Manchester) tutorial pages: 93-94.

The link for the tutorial is already in the reference links provided in the presentation (demo) slides on Protégé.

Regards
Mayukh.

(Please close the issue if the query is addressed).

**Comment by ghost** [comment]
Thank you @MayukhBagchiTrento.

We read the Manchester tutorial and in the first verison of our ontology (without the using of KOS system provided by @simone-bocca ) there weren't problems. Now, we have some doubts about the formalization of the name for the individual that we have to put in the ennumaration classes. Infact in the ontology that we downoladed from the new system there are some examples of this individuals but we are not able to understand the formalization of the name. 

I attached a photo for mor clarity:
![photo_2020-11-24_15-49-55](https://user-images.githubusercontent.com/44431441/100110081-d8963380-2e6c-11eb-8b14-71dd73552ead.jpg)


Taanks you again, 

_Sergio_
