### ISSUE TITLE
Upload problem of the rdf/owl with the kbimporter API

### ISSUE THREAD

**Issue by ghost** [UNITN-KDI-2020/unitn-kdi-2020-room#14]
Dear all,

I'm KE of geospatial group and i'm writeing you beacuse we have a issue related to the upload of the rdf/owl with the kbimporter API. 

Infact, when we try we have this error: 
![photo_2020-11-25_20-20-32](https://user-images.githubusercontent.com/44431441/100273060-76b4f700-2f5c-11eb-84e0-04e04651630e.jpg)

Haw can we resolve ? 

Thank you in advance.

**Comment by simone-bocca** [comment]
Dear Sergio,

can you send me the owl file you are trying to import ?

Thanks
Simone

**Comment by ghost** [comment]
Dear Simone, 
I'll send you by email.

Thanks
