### ISSUE TITLE
Change group project

### ISSUE THREAD

**Issue by LorenzoDonini997** [UNITN-KDI-2020/unitn-kdi-2020-room#2]
Good evening Professor,
I'm sorry for the drawback but I would like to join the GeoSpatial group work since probability I've made a mistake by filling the form.

Thanks in advance have a nice day.

Lorenzo Donini

**Comment by simone-bocca** [comment]
Hi Lorenzo @LorenzoDonini997 
I published the first version of the teams, in which you are assigned to the project on "Medical domain - Covid".
Regarding your request to be assigned to the GeoSpatial project, I kindly ask you to check if someone in the GeoSpatial project want to exchange his position with you.

The person involved in the GeoSpatial domain (right now) are:
Michele Tessari
Daniele Mattedi
Sergio Povoli
Matteo Bortolon

Let me know here if you will receive answer from them.

Best regards
Simone Bocca
