### ISSUE TITLE
Problems with poetry setup

### ISSUE THREAD

**Issue by devis12** [UNITN-KDI-2020/unitn-kdi-2020-room#4]
I managed to install on Win10 the tools and frameworks you asked us to, however when I run the first simple poetry script (i.e. hello world which test the correct import of the library "arrow" in the virtual environment), I got this:

`  PS C:\Users\devis\Documents\Magistrale_DISI_unitn\KnowledgeDataIntegration\my_project> poetry run my_project/index.py

   OSError

  [WinError 193] %1 non è un'applicazione di Win32 valida

  at ~\AppData\Local\Programs\Python\Python38\lib\subprocess.py:1307 in _execute_child
      1303│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1304│ 
      1305│             # Start the process
      1306│             try:
    → 1307│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1308│                                          # no special security
      1309│                                          None, None,
      1310│                                          int(not close_fds),
      1311│                                          creationflags,
`

I figured it might be something related to my environment setup, but I can't solve it since my knowledge of Python & co. is really poor.

**Comment by devis12** [comment]
Sorry if I didn't put assignee, projects and labels, but apparently I can't (even if I'm part of the KDI-2020 organization)

**Comment by zambotn** [comment]
I'm not a windows expert however i remember paths should have "\\" instead of "/". If this doesn't solve
@devis12 which method you used to install the environment? Anaconda or Native+Pip (or using the WSL2)?

**Comment by devis12** [comment]
Yes, you're right, but unfortunately that doesn't solve the issue...
I used Anaconda

**Comment by zambotn** [comment]
I think on poetry they specify a possible solution to this.

https://github.com/python-poetry/poetry/issues/1317#issuecomment-650741995, can you try this solution too?

**Comment by devis12** [comment]
I don't know why I didn't stumbled upon this one... sorry for the trouble
In this way, it works... still not very clear to me why, but I'll check better the docs of poetry

**Comment by zambotn** [comment]
The reason is that windows doesn't recognise text files as executables. You have to provide explicitly an executable 'cause Windows is a bit dumb and you have to specify which _executable_ it has to execute and passing a _python file_ is simply not enough for it (it was a legacy security feature of the M$ OS).
