### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by TEXflip** [UNITN-KDI-2020/unitn-kdi-2020-room#6]
We didn't understand well how to do the evaluation part, what are the inputs of the metrics? Can you do some examples?

Is the evaluation part mandatory for the assessment of tomorrow or for the future assessment?

**Comment by maurodragoni** [comment]
As answered during the Q&A session of Thursday, there will be an update about the evaluation part as we explain which are the input sets for both alpha and beta.
The evaluation is not part of this assessment, but it will be part of the final one of course.
I think that in less than a couple of week there will be further details posted about it.
