### ISSUE TITLE
UKC explorer & Importer

### ISSUE THREAD

**Issue by devis12** [UNITN-KDI-2020/unitn-kdi-2020-room#7]
In the lecture regarding Formal Modeling and in the one talking directly about UKC, it is shown multiple times a software for exploring the UKC knowledge graph (which I suppose have to be downloaded from here https://github.com/kbatsuren/CogNet), but I can't find the link for downloading it.

The same goes for the Importer, which is mentioned and described in a dedicated lecture, but it's never told from where it was download and how it was installed.

If you could kindly share the links, it'd be appreciated

P.S. I apologise in advance if they're posted or been mentioned somewhere and I wasn't able to find them

**Comment by mbortolon97** [comment]
I totally agree with you. Also some resources are missing for me. I think its http://uk.disi.unitn.it:8080/ukcui/wordnetview.htm but UniTN VPN necessary to access it are unavailable.

**Comment by yaminic7** [comment]
The following are the points to be noted, 

1. to explore the UKC (contents mentioned in the slides), you can use http://linguarena.eu/#!/ website. 
2. the details regarding the importer tool (where to find it and so) will be provided soon with instructions. 
3. to access via VPN (if and when required), here are the instructions https://icts.unitn.it/vpn.  

Hope this helps.
