### ISSUE TITLE
iTelos repository location

### ISSUE THREAD

**Issue by mbortolon97** [UNITN-KDI-2020/unitn-kdi-2020-room#8]
Good morning,
We have watched the slides but we have difficulty to fully understand some points. In the slide 18 of lecture 14 it is present the following sentence:

> In the L4 Generation the Knowledge Engineer aims to obtain a new formal version of the knowledge schema (L4) starting from the Teleology, selected from the iTelos Repositories, and the L4 informal schema produced as output of the previous phase. 

So for our understanding, we need to start from an established iTelos repository. Are we right? If yes, where can we find this repositories? Or like the year before we need to start from internet available ontologies like [https://schema.org/docs/schemaorg.owl](https://schema.org/docs/schemaorg.owl)
Thanks in advance

**Comment by MayukhBagchiTrento** [comment]
Dear All,

"In the L4 Generation the Knowledge Engineer aims to obtain a new formal version of the knowledge schema (L4) starting from the Teleology, selected from the iTelos Repositories, and the L4 informal schema produced as output of the previous phase. " 

With respect to the above explanation, please note the following points:-

(1) The iTelos Repository is under development. It is an integral part of the methodology, so it was mentioned. Please see point (2), which will be sufficient for your tasks.

(2) The teleologies are the reference ontologies (knowledge resources) given to you during the project exposition lectures. While creating the class hierarchy (class is same as etype in our context), object properties and data properties, you have to refer to the reference teleologies and align your formal L4 schema with them (the reference ones) as much as possible [align in the practical sense means:- if you have etypes in your schema which is semantically same as a corresponding class in the reference teleology, use the class from the reference teleology; similar approach for object and data properties as well]. If you've new etypes and properties, it is obvious that you'll have to create them anew (or, you may also consult standard ontologies like schema.org to reuse some of their components).

#Please note the slide on knowledge resources in the project illustration lectures for an inexhaustive list of reference teleologies; you may also use other standard knowledge resources like schema.org ( your choice )

#For building the formal L4 schema from informal EER model, please go through the Protege manchester tutorial thoroughly

A repertoire of high quality ontologies which you can consult for your work:-

https://lov.linkeddata.es/dataset/lov/
