### ISSUE TITLE
Ontology creation process

### ISSUE THREAD

**Issue by mbortolon97** [UNITN-KDI-2020/unitn-kdi-2020-room#9]
Good morning,
Yesterday evening we saw the new slide that Simone Bocca published, but the process explained inside is incoherent with the process explained previously (W7.L14.M5.T14.All).
Considering the issue #8 that say the iTelos repositories is not available yet, we have follow this process:
```
L4 (Creation of the ontology classes, relationships and attributes using Protégé) ===> L1/L2 (add annotation using UKC ontology and add to UKC the missing classes)
```
The new process that Simone Bocca explained yesterday instead can be summarised as:
```
L1/L2 (Select the classes with the attributes and relations using UKC) ===> Export to Protégé using the RDF format
```
This is coerent with the initial slides if we consider UKC as a iTelos repository.

At the moment we are following the first process and we are at a good point where the only missing part is the L1/L2 annotations, and the ontology in review status by Dr. Mayukh. 
**At this point we are wondering what of the two processes to follow?**
Thanks in advance for your help
Matteo Bortolon

**Comment by simone-bocca** [comment]
Dear Matteo @mbortolon97 

Can we consider this issue closed or you need more details on that ?
Let me know, otherwise I'll close this issue in 24h.

Thanks
Simone Bocca
